[package]
name = "cli"
version = "0.1.0"
authors = ["Viktor Kuroljov <viktor.konsta@gmail.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3" }
serde = { version = "1.0" }
colored = { version = "2.0" }
serde_json = { version = "1.0" }

dtflib = { path = "../dtflib" }
